project:
  type: website
  output-dir: docs
  resources:
    - cv.pdf
    - logo_i02.png
    - images/**
  render:
    - index.qmd
    - sobre-mi.qmd
    - proyectos.qmd

website:
  title: "Ignacio Isa"
  favicon: logo_i02.png

  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: sobre-mi.qmd
        text: Sobre mí
      - href: proyectos.qmd
        text: Proyectos
      - href: cv.pdf
        text: Currículum

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

