project:
  type: website
  output-dir: docs
  resources:
    - cv.pdf
    - logo_i02.png
    - images/**
  render:
    - index.qmd
    - about.qmd
    - projects.qmd
    - es/index.qmd
    - es/sobre-mi.qmd
    - es/proyectos.qmd

website:
  title: "Ignacio Isa"
  favicon: logo_i02.png

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: cv.pdf
        text: Curriculum Vitae
    right:
      - text: Language
        menu:
          - text: English
            href: index.qmd
          - text: Español
            href: es/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

